### ISSUE TITLE
Please add a license to the repo

### ISSUE THREAD

**Issue by beckettsean** [cloudfoundry/volume-mount-options#2]
Please add a license to this repo so it can be responsibly used by others. Without a license present we must assume you reserve all rights.

**Comment by kdykeman** [comment]
@davewalter @paulcwarren I submitted PR #3 to add the Apache 2.0 LICENSE and NOTICE files similar those for other CloudFoundry repos.

**Comment by paulcwarren** [comment]
Thanks @beckettsean.  We'll pick this up and merge your PR soonest.
